# These are supported funding model platforms

github: wiimag
custom: ["https://www.paypal.com/donate/?business=9BP5HBC9GFYYA&amount=10&no_recurring=0&item_name=I+make+applications+for+the+love+of+programming.+You+can+support+me+to+continue+the+developement.+Thanks+for+your+support.+%F0%9F%9A%80&currency_code=CAD", 'https://eodhistoricaldata.com/r/?ref=PF9TZC2T']

#patreon: # Replace with a single Patreon username
