# These are supported funding model platforms

github: wiimag
custom: ['https://wallet.wiimag.com', 'https://eodhistoricaldata.com/r/?ref=PF9TZC2T']

#patreon: # Replace with a single Patreon username
