name: Build MacOS

on:
  push:
#  pull_request:
#    types: [review_requested, ready_for_review]
  schedule:
    # min hours day(month) month day(week)
    - cron: '0 4 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: [self-hosted, macos]

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Build Infineis (Xcode)
        run: xcodebuild -workspace projects/xcode/infineis.xcworkspace -scheme "infineis Release" build SYMROOT="../../build" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
#      - name: Upload Infineis.app
#        if:
#        uses: actions/upload-artifact@v3
#        with:
#          name: infineis-macos-release
#          path: |
#            build
#            !build/*.a
#          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
#          retention-days: 1

# Notes for later
# productbuild --component MyApp.app /Applications --sign "Developer ID Installer: My Company (ABCDEFGHIJ)" MyApp.pkg
