name: Test MacOS

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: [self-hosted, macos]
    environment: tests

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - name: Build Infineis (Xcode)
        run: xcodebuild -quiet -workspace projects/xcode/infineis.xcworkspace -scheme "infineis Debug" build SYMROOT="../../build"

      - name: Run tests
        env:
          API_KEY: ${{ secrets.INFINEIS_TESTS_APIKEY }}
        run: |
          ./build/Infineis.app/Contents/MacOS/Infineis --run-tests --build-machine --verbose  --apikey "$API_KEY"

      - name: Print test logs
        if: always()
        shell: bash
        run: |
          cat artifacts/tests.log

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: infineis-osx-test-results
          path: |
            **/*.log
          if-no-files-found: error
          retention-days: 2
      - name: Delete Previous deployments (OSX)
        uses: actions/github-script@v6
        with:
          script: |
            const deployments = await github.rest.repos.listDeployments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha
            });
            await Promise.all(
              deployments.data.map(async (deployment) => {
                await github.rest.repos.createDeploymentStatus({ 
                  owner: context.repo.owner, 
                  repo: context.repo.repo, 
                  deployment_id: deployment.id, 
                  state: 'inactive' 
                });
                return github.rest.repos.deleteDeployment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  deployment_id: deployment.id
                });
              })
            );
